replicaCount: 3

image:
  repository: ghcr.io/elritz/managing-temp
  pullPolicy: Always
  tag: main

nameOverride: graphql
fullnameOverride: graphql

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: managing-temp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
