name: Pull Request Check Deploy

on:
  pull_request:
    paths:
      - "deploy/**"

jobs:
  # See GH Action: https://github.com/helm/chart-testing-action
  helm-lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Helm lint
        id: list-changed
        run: helm lint ./deploy/subgraph-b
